
#docker build -f Dockerfile.in .


FROM fedora:32

LABEL maintainer="The KubeVirt Project <kubevirt-dev@googlegroups.com>"

RUN dnf install -y dnf-plugins-core && \
    dnf install -y \
      qemu-kvm \
      genisoimage \
      selinux-policy selinux-policy-targeted \
      nftables \
      iptables \
      meson \
      git \
      augeas \
      make && \
    dnf update -y libgcrypt && \
    dnf builddep libvirt -y && \
    dnf clean all

COPY augconf /augconf
RUN augtool -f /augconf

COPY libvirtd.sh /libvirtd.sh
RUN chmod a+x /libvirtd.sh

RUN git clone https://gitlab.com/nertpinx/libvirt.git
RUN cd libvirt && git fetch -v && git checkout unix_migration && meson build -Dsystem=true --prefix=/usr && ninja -C build && sudo ninja -C build install

RUN setcap CAP_NET_BIND_SERVICE=+eip "/usr/bin/qemu-kvm"

CMD ["/libvirtd.sh"]
